# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    AppBundle.locale_listener:
        class: AppBundle\EventListener\LocaleListener
        arguments: ["@service_container"]
        tags:
            - { name: kernel.event_subscriber }
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
